# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('published', models.BooleanField(default=False)),
                ('base_name', models.CharField(max_length=4096, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='photos/')),
                ('format', models.CharField(choices=[('JPEG', 'JPEG'), ('WEBP', 'WebP')], max_length=4)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Photo')),
            ],
        ),
    ]
