# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photofile',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
