# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photofile_exif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='base_name',
        ),
        migrations.AlterField(
            model_name='photofile',
            name='format',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
