# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20170610_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='photofile',
            name='processor',
            field=models.CharField(default='USER_UPLOAD', max_length=2048),
        ),
    ]
