# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 18:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photofile_processor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photofile',
            name='exif',
        ),
        migrations.AddField(
            model_name='photo',
            name='exif',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
